openapi: 3.0.1
info:
  title: '@jupiterone/graph-pagerduty'
  description: A graph conversion tool for https://www.pagerduty.com/.
  x-cortex-git:
    github:
      repository: JupiterOne/graph-pagerduty
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-pagerduty'
